language: ruby
before_script:
  - "mysql -e 'create database lhm;'"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
sudo: false
matrix:
  fast_finish: true
gemfile:
  - gemfiles/ar-3.2_mysql.gemfile
  - gemfiles/ar-3.2_mysql2.gemfile
